### ISSUE TITLE
CameraCaptureExample gives "Error compiling for board ESP32-CAM"

### ISSUE THREAD

**Issue by Sikkens99** [eloquentarduino/EloquentSurveillance#10]
Compiling "EloquentSurveillance/examples/CameraCaptureExample/CameraCaptureExample.ino" [with camera.aithinker();]
results in "error compiling for board ESP32-CAM".  
What could be the problem here?

**Comment by lolo-b** [comment]
same for me. I put camera.aithinker() and I have these errors. Same results with camera.m5wide();

In file included from c:\Users\Utilisateur\Documents\Arduino\libraries\EloquentSurveillance\src/EloquentSurveillance.h:14:0,
                 from C:\Users\Utilisateur\AppData\Local\Temp\.arduinoIDE-unsaved202357-15300-1u282k8.qe5p\CameraStreamServerExample\CameraStreamServerExample.ino:3:
c:\users\utilisateur\documents\arduino\libraries\eloquentsurveillance\src\motion.h:443:104: error: 'uitn16_t' has not been declared
         void forEachBlock(Callback callback, Reducer& reducer, uint16_t x, uint16_t y, uint16_t width, uitn16_t height, uint8_t size) {
                                                                                                        ^
c:\users\utilisateur\documents\arduino\libraries\eloquentsurveillance\src\motion.h: In member function 'void EloquentSurveillance::Motion::locate2()':
c:\users\utilisateur\documents\arduino\libraries\eloquentsurveillance\src\motion.h:412:61: error: expected primary-expression before ';' token
             for (uint16_t y = _location.y > blockSize / 2 ? ; y < _location.y + blockSize; y += blockSize / 2) {
                                                             ^
c:\users\utilisateur\documents\arduino\libraries\eloquentsurveillance\src\motion.h:412:61: error: expected ':' before ';' token
c:\users\utilisateur\documents\arduino\libraries\eloquentsurveillance\src\motion.h:412:61: error: expected primary-expression before ';' token
c:\users\utilisateur\documents\arduino\libraries\eloquentsurveillance\src\motion.h:418:47: error: 'W' was not declared in this scope
                         uint32_t offset = j * W;
                                               ^

**Comment by Patriboom** [comment]
For 
`for (uint16_t y = _location.y > blockSize / 2 ? ; y < _location.y + blockSize; y += blockSize / 2) {`

The question mark has to be removed.

Since those errors are present in versions 1.0.15  and 1.0.14
I'm back with 1.0.13 which works good

**Comment by Patriboom** [comment]
All corrections are given in https://github.com/eloquentarduino/EloquentSurveillance/issues/9  
There are three lines to correct

**Comment by Sikkens99** [comment]
Thanks for all reactions, my problem was solved.
